export const siteConfig = {
  productName: "limAPI",
  brandLine: "一个 API，连接每一种 AI",
  englishLine: "One API, Connect Every AI.",
  companyName: "杭州自然变换科技有限公司",
  copyright: "© 2026 杭州自然变换科技有限公司 All Rights Reserved.",
  icp: "浙ICP备2021031999号",
  enterpriseApps: [
    { name: "iSee Dev", type: "编程平台", short: "ID", href: "/login?app=isee-dev" },
    { name: "QQSora", type: "视频生成平台", short: "QS", href: "/login?app=qqsora" },
    { name: "limAPI 企业版", type: "企业中转站", short: "AA", href: "/login?app=limapi-enterprise" },
  ],
} as const;

export const demoModels = [
  {
    id: "atlas-chat-v2",
    name: "Atlas Chat V2",
    provider: "Northstar AI（示例）",
    mark: "AT",
    summary: "通用对话、工具调用与结构化输出的演示模型。",
    status: "演示可用",
    statusTone: "success",
    capabilities: ["文本", "工具", "JSON"],
    context: "128K",
    inputPrice: "¥2.00 / 1M",
    outputPrice: "¥8.00 / 1M",
  },
  {
    id: "orion-reasoner-r1",
    name: "Orion Reasoner R1",
    provider: "Polaris Labs（示例）",
    mark: "OR",
    summary: "复杂推理、数学分析与任务规划的演示模型。",
    status: "演示繁忙",
    statusTone: "warning",
    capabilities: ["推理", "数学", "工具"],
    context: "128K",
    inputPrice: "¥4.00 / 1M",
    outputPrice: "¥16.00 / 1M",
  },
  {
    id: "prism-vision-pro",
    name: "Prism Vision Pro",
    provider: "Canvas AI（示例）",
    mark: "PV",
    summary: "视觉理解、文档解析与结构化提取的演示模型。",
    status: "演示可用",
    statusTone: "success",
    capabilities: ["文本", "视觉", "JSON"],
    context: "256K",
    inputPrice: "¥3.00 / 1M",
    outputPrice: "¥12.00 / 1M",
  },
  {
    id: "swift-mini",
    name: "Swift Mini",
    provider: "Nimbus（示例）",
    mark: "SM",
    summary: "轻量、快速，适合批量文本任务的演示模型。",
    status: "演示可用",
    statusTone: "success",
    capabilities: ["文本", "工具"],
    context: "64K",
    inputPrice: "¥0.30 / 1M",
    outputPrice: "¥1.20 / 1M",
  },
  {
    id: "lingxi-code-max",
    name: "Lingxi Code Max",
    provider: "Lingxi Lab（示例）",
    mark: "LC",
    summary: "面向代码生成、解释与重构的演示模型。",
    status: "演示可用",
    statusTone: "success",
    capabilities: ["代码", "推理", "工具"],
    context: "200K",
    inputPrice: "¥1.50 / 1M",
    outputPrice: "¥6.00 / 1M",
  },
  {
    id: "nebula-long-1m",
    name: "Nebula Long 1M",
    provider: "Horizon AI（示例）",
    mark: "NL",
    summary: "超长文档处理与信息抽取的演示模型。",
    status: "演示维护",
    statusTone: "neutral",
    capabilities: ["长文本", "JSON"],
    context: "1M",
    inputPrice: "¥2.40 / 1M",
    outputPrice: "¥9.60 / 1M",
  },
] as const;
